# Generated by Django 4.0.2 on 2022-03-04 18:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_image',
            field=models.ImageField(blank=True, default=core.models.get_default_account_image, max_length=255, null=True, upload_to=core.models.get_account_image_filepath),
        ),
    ]
